### ISSUE TITLE
Components are not re-usable as shown in the component library

### ISSUE THREAD

**Issue by pruthvirajmv** [kotesh-arya/Handy_UI-Component_Library#28]
Hi Kotesh,
When I copy the code provided in your component library for the below components, they are not looking same as displayed in the component library, kindly look into it & fix
- Vertical Card
- Success Input 
- Warning Input 
- Error Input
Mostly you have to cross check the class names
Thanks and keep coding

**Comment by kotesh-arya** [comment]
Hello Pruthvi,
Updated the changes that are required 👍🏻
